# Generated by Django 2.1.2 on 2018-10-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase_investigadores',
            name='content',
        ),
        migrations.RemoveField(
            model_name='clase_investigadores',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='clase_investigadores',
            name='autor',
            field=models.CharField(default='Escribe el Nombre del Autor', max_length=32),
        ),
        migrations.AddField(
            model_name='clase_investigadores',
            name='categoria',
            field=models.CharField(choices=[('Ciencias Computacionales', 'Ciencias Computacionales'), ('Ciencias de la Tierra', 'Ciencias de la Tierra'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Ciencias Medicas', 'Ciencias Medicas')], default='Ciencias Computacionales', max_length=32),
        ),
        migrations.AddField(
            model_name='clase_investigadores',
            name='titulo',
            field=models.CharField(default='Escribe el Titulo', max_length=32),
        ),
    ]
