# Generated by Django 2.1.2 on 2018-10-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181030_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='consulta_investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Escribe el Titulo', max_length=32)),
                ('autor', models.CharField(default='Escribe el Nombre del Autor', max_length=32)),
                ('categoria', models.CharField(default='Ciencias Computacionales', max_length=32)),
            ],
        ),
    ]
