# Generated by Django 2.1.2 on 2018-10-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_consulta_investigacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consulta_investigacion',
        ),
    ]
