# Generated by Django 2.1.2 on 2018-10-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_consulta_investigacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clase_investigadores',
            new_name='Archivos_Investigacion',
        ),
    ]
